
---
- name: Install Apache2 and upload MyWebsite
  become: yes
  hosts: all

  vars: 
    source_html_file: ./MyWebsite/index.html
    source_css_file: ./MyWebsite/style.css
    source_img_file: ./MyWebsite/img.jpg
    destination: /var/www/html 

  tasks: 
  - name: Check and print OS family
    debug: var=ansible_pkg_mgr

  - name: Update cache for Debian
    apt: update_cache=yes
    when: ansible_pkg_mgr == "apt"

  - name: Install apache2 webserver for Debian
    apt: name=apache2 state=latest
    when: ansible_pkg_mgr == "apt"

  - name: Update cache for RedHat
    dnf: update_cache=yes
    when: ansible_pkg_mgr == "dnf"

  - name: Install apache2 webserver for RedHat
    dnf: name=httpd state=latest
    when: ansible_pkg_mgr == "dnf"

  - name: Copy MyWebsite html to servers
    copy: src={{ source_html_file }} dest={{ destination }} mode=0555

  - name: Copy MyWebsite css to servers
    copy: src={{ source_css_file }} dest={{ destination }} mode=0555
  
  - name: Copy Background image to servers
    copy: src={{ source_img_file }} dest={{ destination }} mode=0555

  - name: Enable apache2 webserver for Debian
    service: name=apache2 enabled=yes
    when: ansible_pkg_mgr == "apt"

  - name: Enable apache2 webserver for RedHat
    service: name=httpd enabled=yes
    when: ansible_pkg_mgr == "dnf"
